### ISSUE TITLE
Impossible to build

### ISSUE THREAD

**Issue by djcaesar9114** [jwillmer/jekyllDecent#24]
Hi there!
I run `jekyll serve` command and I get this result:

```
WARN: Unresolved specs during Gem::Specification.reset:
      rouge (~> 1.7)
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /home/cesar/projets/jekyll/jekyllDecent-gh-pages/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-mentions or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-mentions' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
jekyll 3.1.6 | Error:  jekyll-mentions
```

**Comment by jwillmer** [comment]
I think the error msg tells you the problem:

> It looks like you don't have jekyll-mentions or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-mentions' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!

Remove jekyll mentions from the `/home/cesar/projets/jekyll/jekyllDecent-gh-pages/_config.yml` file or install it and all will run smoothly.

**Comment by jwillmer** [comment]
I close that because of no response by the creator of the bug.
