### ISSUE TITLE
Enhancement for Disqus and MathJax

### ISSUE THREAD

**Issue by svanimisetti** [jwillmer/jekyllDecent#33]
For my personal [site](https://svanimisetti.in/), I am using [So Simple](https://mademistakes.com/work/so-simple-jekyll-theme/) theme. I noticed that it allows for adding Disqus board for article. Also, the theme allows for using MathJax for setting up mathematical equations on the post.

Does your theme already support this? If not, can you look at some enhancements?

**Comment by jwillmer** [comment]
For Disqua support you need to configure the `_config.yml` and enable it for each post separately. You can find the [description and demo on this page](http://jwillmer.github.io/jekyllDecent/blog/features/YAML-Features).
I don't know MathJax but I can see the use for it. I will create a new issue to implement it but I can't promise you to make it right away.
