### ISSUE TITLE
How to add chinese language support

### ISSUE THREAD

**Issue by fengguangle** [jwillmer/jekyllDecent#49]
Hi,jwillmer,thanks for you jekyll theme.
I am beginner for jekyll.
When I set title and meautitle is chinese,I can't get post page at website,why?

**Comment by jwillmer** [comment]
This should have nothing to do with the theme. I guess you might have changed the file encoding - does it work if you set an English title?

**Comment by fengguangle** [comment]
thanks, I should change the post encoding to UTF-8, work well.  Awesome theme.
