### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by kleinzcy** [jwillmer/jekyllDecent#51]
Hi!
Thanks to your template. I missed a question. 
![image](https://user-images.githubusercontent.com/35723500/60394710-514f6e00-9b5b-11e9-9ffb-fcf1b46c388e.png)
Why the first line is empty?
my source code is
``` 
<pre class="line-numbers language-javascript"><code>
......
</code></pre>
```

I would appreciate it if you can help me.
Thanks!

**Comment by jwillmer** [comment]
can u please reference the code part in the repository? I have no idea there this is coming from.

**Comment by kleinzcy** [comment]
@jwillmer The code is at the bottom of _posts/Feature/.

**Comment by jwillmer** [comment]
it's not empty for me. look at the [demo page](https://jwillmer.github.io/jekyllDecent/blog/features/Features) and compare it with the [source](https://raw.githubusercontent.com/jwillmer/jekyllDecent/gh-pages/_posts/2016-05-07-Features.md). 
The trick is to start your code directly after the tag.

**Comment by kleinzcy** [comment]
Thanks,I solve it.
