### ISSUE TITLE
intergrating FastPages.ai 

### ISSUE THREAD

**Issue by AllieUbisse** [jwillmer/jekyllDecent#54]
# Add FastPages.ai 
i like the fast pages feature for blogging, is it possible to add the  **github action** to convert Jupyter notebooks to blogs ?

see the example blog below.
[fastpages blog](https://fastpages.fast.ai/)
[Introducing fastpages](https://fastpages.fast.ai/fastpages/jupyter/2020/02/21/introducing-fastpages.html#Setting-Up-Fastpages)

**Comment by jwillmer** [comment]
I believe you can just fork fastpage and then copy&paste the layout of jekyllDecent. You can also make a `fastpageDecent` theme by forking this project and add the needed customization.

**Comment by AllieUbisse** [comment]
I'll look in to it. Thanks...🥇
