### ISSUE TITLE
a11y: sufficient contrast

### ISSUE THREAD

**Issue by Seirdy** [jwillmer/jekyllDecent#68]
Elements such as timestamps in the list of posts are very difficult to see: they have extremely low contrast. Their size is also set in absolute units (px) instead of relative units (em, rem, `%`), so they might not have their size increased by a "minimum-size" browser preference; this makes their low contrast a much more significant issue, as small elements need higher contrast to be visible.

I'd recommend using [a contrast calculator](https://www.myndex.com/APCA/) to pick a foreground color with better perceptual contrast.

**Comment by jwillmer** [comment]
Good idea! However I have zero time this year to do anything on the matter. If you like to provide a pull request I will be happy to review and merge it. Otherwise I'm afraid I have to postpone this for some time.

**Comment by Seirdy** [comment]
Just opened PR #69 which should fix this.

-- 
Seirdy (https://seirdy.one)

**Comment by jwillmer** [comment]
Thank you for the contribution :)
